import { API_APIKEY,API_AUTHDOMAIN,API_PROJECTID,API_STORAGEBUCKET,API_MESSAGINGSENDERID,API_APPID} from '@env';

export default { 
    API_APIKEY,
    API_AUTHDOMAIN,
    API_PROJECTID,
    API_STORAGEBUCKET,
    API_MESSAGINGSENDERID,
    API_APPID
}